name: Build and Attach Runtimes to Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    strategy:
      matrix:
        runtime:
          # TODO: Add parachain runtimes
          - { name: westend, package: westend-runtime, path: relay/westend }
          - { name: rococo, package: rococo-runtime, path: relay/rococo }
        build_type:
          # No prefix indicates a release build
          - { prefix: "", build_opts: "--features on-chain-release-build" } 
          - { prefix: DEBUG_BUILD__, build_opts: "--features try-runtime" }

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build ${{ matrix.runtime.name }}
      id: srtool_build
      uses: chevdor/srtool-actions@v0.8.0
      env:
        BUILD_OPTS: ${{ matrix.build_type.build_opts }}
      with:
        chain: ${{ matrix.runtime.name }}
        package: ${{ matrix.runtime.package }}
        runtime_dir: ${{ matrix.runtime.path }}
        profile: "production"

    - name: Upload Runtime to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ matrix.runtime.path }}/target/srtool/production/wbuild/$PACKAGE_NAME/$RUNTIME_BLOB_NAME
        asset_name: ${{ matrix.build_type.prefix }}$RUNTIME_BLOB_NAME
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGE_NAME: ${{ matrix.runtime.package }}
        RUNTIME_BLOB_NAME: $(echo $PACKAGE_NAME | sed 's/-/_/g').compact.compressed.wasm
